name: CI

on: [push, pull_request]

jobs:

  test_os:
    name: OS ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        run: ./mvnw -V --no-transfer-progress clean verify javadoc:javadoc
